from __future__ import annotations

from dataclasses import dataclass
from typing import Final


@dataclass(frozen=True, slots=True)
class CountryMetadata:
    """Normalized metadata for one football national-team entity."""

    canonical_name: str
    iso_code_2: str | None
    fifa_code: str | None
    confederation: str | None
    is_fifa_member: bool


COUNTRY_METADATA_MAP: Final[dict[str, CountryMetadata]] = {
    "AB": CountryMetadata("Abkhazia", None, None, None, False),
    "AD": CountryMetadata("Andorra", "AD", "AND", "UEFA", True),
    "AE": CountryMetadata("United Arab Emirates", "AE", "UAE", "AFC", True),
    "AF": CountryMetadata("Afghanistan", "AF", "AFG", "AFC", True),
    "AG": CountryMetadata("Antigua and Barbuda", "AG", "ATG", "CONCACAF", True),
    "AI": CountryMetadata("Anguilla", "AI", "AIA", "CONCACAF", True),
    "AL": CountryMetadata("Albania", "AL", "ALB", "UEFA", True),
    "AM": CountryMetadata("Armenia", "AM", "ARM", "UEFA", True),
    "AO": CountryMetadata("Angola", "AO", "ANG", "CAF", True),
    "AR": CountryMetadata("Argentina", "AR", "ARG", "CONMEBOL", True),
    "AS": CountryMetadata("American Samoa", "AS", "ASA", "OFC", True),
    "AT": CountryMetadata("Austria", "AT", "AUT", "UEFA", True),
    "AU": CountryMetadata("Australia", "AU", "AUS", "AFC", True),
    "AW": CountryMetadata("Aruba", "AW", "ARU", "CONCACAF", True),
    "AZ": CountryMetadata("Azerbaijan", "AZ", "AZE", "UEFA", True),
    "BA": CountryMetadata("Bosnia and Herzegovina", "BA", "BIH", "UEFA", True),
    "BB": CountryMetadata("Barbados", "BB", "BRB", "CONCACAF", True),
    "BD": CountryMetadata("Bangladesh", "BD", "BAN", "AFC", True),
    "BE": CountryMetadata("Belgium", "BE", "BEL", "UEFA", True),
    "BF": CountryMetadata("Burkina Faso", "BF", "BFA", "CAF", True),
    "BG": CountryMetadata("Bulgaria", "BG", "BUL", "UEFA", True),
    "BH": CountryMetadata("Bahrain", "BH", "BHR", "AFC", True),
    "BI": CountryMetadata("Burundi", "BI", "BDI", "CAF", True),
    "BJ": CountryMetadata("Benin", "BJ", "BEN", "CAF", True),
    "BL": CountryMetadata("Saint Barthelemy", "BL", None, None, False),
    "BM": CountryMetadata("Bermuda", "BM", "BER", "CONCACAF", True),
    "BN": CountryMetadata("Brunei", "BN", "BRU", "AFC", True),
    "BO": CountryMetadata("Bolivia", "BO", "BOL", "CONMEBOL", True),
    "BQ": CountryMetadata("Bonaire", "BQ", "BON", "CONCACAF", True),
    "BR": CountryMetadata("Brazil", "BR", "BRA", "CONMEBOL", True),
    "BS": CountryMetadata("Bahamas", "BS", "BAH", "CONCACAF", True),
    "BT": CountryMetadata("Bhutan", "BT", "BHU", "AFC", True),
    "BW": CountryMetadata("Botswana", "BW", "BOT", "CAF", True),
    "BY": CountryMetadata("Belarus", "BY", "BLR", "UEFA", True),
    "BZ": CountryMetadata("Belize", "BZ", "BLZ", "CONCACAF", True),
    "CA": CountryMetadata("Canada", "CA", "CAN", "CONCACAF", True),
    "CC": CountryMetadata("Cocos Islands", "CC", None, None, False),
    "CD": CountryMetadata("DR Congo", "CD", "COD", "CAF", True),
    "CF": CountryMetadata("Central African Republic", "CF", "CTA", "CAF", True),
    "CG": CountryMetadata("Congo", "CG", "CGO", "CAF", True),
    "CH": CountryMetadata("Switzerland", "CH", "SUI", "UEFA", True),
    "CI": CountryMetadata("Ivory Coast", "CI", "CIV", "CAF", True),
    "CK": CountryMetadata("Cook Islands", "CK", "COK", "OFC", True),
    "CL": CountryMetadata("Chile", "CL", "CHI", "CONMEBOL", True),
    "CM": CountryMetadata("Cameroon", "CM", "CMR", "CAF", True),
    "CN": CountryMetadata("China", "CN", "CHN", "AFC", True),
    "CO": CountryMetadata("Colombia", "CO", "COL", "CONMEBOL", True),
    "CR": CountryMetadata("Costa Rica", "CR", "CRC", "CONCACAF", True),
    "CU": CountryMetadata("Cuba", "CU", "CUB", "CONCACAF", True),
    "CV": CountryMetadata("Cape Verde", "CV", "CPV", "CAF", True),
    "CW": CountryMetadata("Curacao", "CW", "CUW", "CONCACAF", True),
    "CX": CountryMetadata("Christmas Island", "CX", None, None, False),
    "CY": CountryMetadata("Cyprus", "CY", "CYP", "UEFA", True),
    "CZ": CountryMetadata("Czech Republic", "CZ", "CZE", "UEFA", True),
    "DE": CountryMetadata("Germany", "DE", "GER", "UEFA", True),
    "DJ": CountryMetadata("Djibouti", "DJ", "DJI", "CAF", True),
    "DK": CountryMetadata("Denmark", "DK", "DEN", "UEFA", True),
    "DM": CountryMetadata("Dominica", "DM", "DMA", "CONCACAF", True),
    "DO": CountryMetadata("Dominican Republic", "DO", "DOM", "CONCACAF", True),
    "DZ": CountryMetadata("Algeria", "DZ", "ALG", "CAF", True),
    "EC": CountryMetadata("Ecuador", "EC", "ECU", "CONMEBOL", True),
    "EE": CountryMetadata("Estonia", "EE", "EST", "UEFA", True),
    "EG": CountryMetadata("Egypt", "EG", "EGY", "CAF", True),
    "EH": CountryMetadata("Western Sahara", "EH", None, None, False),
    "EI": CountryMetadata("Republic of Ireland", None, "IRL", "UEFA", True),
    "EN": CountryMetadata("England", None, "ENG", "UEFA", True),
    "ER": CountryMetadata("Eritrea", "ER", "ERI", "CAF", True),
    "ES": CountryMetadata("Spain", "ES", "ESP", "UEFA", True),
    "ET": CountryMetadata("Ethiopia", "ET", "ETH", "CAF", True),
    "EU": CountryMetadata("Euskadi", None, None, None, False),
    "FI": CountryMetadata("Finland", "FI", "FIN", "UEFA", True),
    "FJ": CountryMetadata("Fiji", "FJ", "FIJ", "OFC", True),
    "FK": CountryMetadata("Falkland Islands", "FK", None, None, False),
    "FM": CountryMetadata("Micronesia", "FM", None, None, False),
    "FO": CountryMetadata("Faroe Islands", "FO", "FRO", "UEFA", True),
    "FR": CountryMetadata("France", "FR", "FRA", "UEFA", True),
    "GA": CountryMetadata("Gabon", "GA", "GAB", "CAF", True),
    "GD": CountryMetadata("Grenada", "GD", "GRN", "CONCACAF", True),
    "GE": CountryMetadata("Georgia", "GE", "GEO", "UEFA", True),
    "GF": CountryMetadata("French Guiana", "GF", "GUF", "CONCACAF", True),
    "GH": CountryMetadata("Ghana", "GH", "GHA", "CAF", True),
    "GI": CountryMetadata("Gibraltar", "GI", "GIB", "UEFA", True),
    "GL": CountryMetadata("Greenland", "GL", None, None, False),
    "GM": CountryMetadata("Gambia", "GM", "GAM", "CAF", True),
    "GN": CountryMetadata("Guinea", "GN", "GUI", "CAF", True),
    "GP": CountryMetadata("Guadeloupe", "GP", "GLP", "CONCACAF", True),
    "GQ": CountryMetadata("Equatorial Guinea", "GQ", "EQG", "CAF", True),
    "GR": CountryMetadata("Greece", "GR", "GRE", "UEFA", True),
    "GT": CountryMetadata("Guatemala", "GT", "GUA", "CONCACAF", True),
    "GU": CountryMetadata("Guam", "GU", "GUM", "AFC", True),
    "GW": CountryMetadata("Guinea-Bissau", "GW", "GNB", "CAF", True),
    "GY": CountryMetadata("Guyana", "GY", "GUY", "CONCACAF", True),
    "HG": CountryMetadata("Hmong", None, None, None, False),
    "HK": CountryMetadata("Hong Kong", "HK", "HKG", "AFC", True),
    "HN": CountryMetadata("Honduras", "HN", "HON", "CONCACAF", True),
    "HR": CountryMetadata("Croatia", "HR", "CRO", "UEFA", True),
    "HT": CountryMetadata("Haiti", "HT", "HAI", "CONCACAF", True),
    "HU": CountryMetadata("Hungary", "HU", "HUN", "UEFA", True),
    "ID": CountryMetadata("Indonesia", "ID", "IDN", "AFC", True),
    "IE": CountryMetadata("Northern Ireland", None, "NIR", "UEFA", True),
    "IL": CountryMetadata("Israel", "IL", "ISR", "UEFA", True),
    "IN": CountryMetadata("India", "IN", "IND", "AFC", True),
    "IQ": CountryMetadata("Iraq", "IQ", "IRQ", "AFC", True),
    "IR": CountryMetadata("Iran", "IR", "IRN", "AFC", True),
    "IS": CountryMetadata("Iceland", "IS", "ISL", "UEFA", True),
    "IT": CountryMetadata("Italy", "IT", "ITA", "UEFA", True),
    "JM": CountryMetadata("Jamaica", "JM", "JAM", "CONCACAF", True),
    "JO": CountryMetadata("Jordan", "JO", "JOR", "AFC", True),
    "JP": CountryMetadata("Japan", "JP", "JPN", "AFC", True),
    "JS": CountryMetadata("Jersey", None, None, None, False),
    "KE": CountryMetadata("Kenya", "KE", "KEN", "CAF", True),
    "KD": CountryMetadata("Kurdistan", None, None, None, False),
    "KG": CountryMetadata("Kyrgyzstan", "KG", "KGZ", "AFC", True),
    "KH": CountryMetadata("Cambodia", "KH", "CAM", "AFC", True),
    "KI": CountryMetadata("Kiribati", "KI", None, None, False),
    "KM": CountryMetadata("Comoros", "KM", "COM", "CAF", True),
    "KN": CountryMetadata("Saint Kitts and Nevis", "KN", "SKN", "CONCACAF", True),
    "KO": CountryMetadata("Kosovo", "XK", "KOS", "UEFA", True),
    "KP": CountryMetadata("North Korea", "KP", "PRK", "AFC", True),
    "KR": CountryMetadata("South Korea", "KR", "KOR", "AFC", True),
    "KW": CountryMetadata("Kuwait", "KW", "KUW", "AFC", True),
    "KY": CountryMetadata("Cayman Islands", "KY", "CAY", "CONCACAF", True),
    "KZ": CountryMetadata("Kazakhstan", "KZ", "KAZ", "UEFA", True),
    "LA": CountryMetadata("Laos", "LA", "LAO", "AFC", True),
    "LB": CountryMetadata("Lebanon", "LB", "LBN", "AFC", True),
    "LC": CountryMetadata("Saint Lucia", "LC", "LCA", "CONCACAF", True),
    "LI": CountryMetadata("Liechtenstein", "LI", "LIE", "UEFA", True),
    "LK": CountryMetadata("Sri Lanka", "LK", "SRI", "AFC", True),
    "LR": CountryMetadata("Liberia", "LR", "LBR", "CAF", True),
    "LS": CountryMetadata("Lesotho", "LS", "LES", "CAF", True),
    "LT": CountryMetadata("Lithuania", "LT", "LTU", "UEFA", True),
    "LU": CountryMetadata("Luxembourg", "LU", "LUX", "UEFA", True),
    "LV": CountryMetadata("Latvia", "LV", "LVA", "UEFA", True),
    "LY": CountryMetadata("Libya", "LY", "LBY", "CAF", True),
    "MA": CountryMetadata("Morocco", "MA", "MAR", "CAF", True),
    "MC": CountryMetadata("Monaco", "MC", None, None, False),
    "MD": CountryMetadata("Moldova", "MD", "MDA", "UEFA", True),
    "ME": CountryMetadata("Montenegro", "ME", "MNE", "UEFA", True),
    "MF": CountryMetadata("Saint Martin", "MF", None, None, False),
    "MG": CountryMetadata("Madagascar", "MG", "MAD", "CAF", True),
    "MH": CountryMetadata("Marshall Islands", "MH", None, None, False),
    "MK": CountryMetadata("North Macedonia", "MK", "MKD", "UEFA", True),
    "ML": CountryMetadata("Mali", "ML", "MLI", "CAF", True),
    "MM": CountryMetadata("Myanmar", "MM", "MYA", "AFC", True),
    "MN": CountryMetadata("Mongolia", "MN", "MNG", "AFC", True),
    "MO": CountryMetadata("Macau", "MO", "MAC", "AFC", True),
    "MP": CountryMetadata("Northern Mariana Islands", "MP", None, "AFC", False),
    "MQ": CountryMetadata("Martinique", "MQ", "MTQ", "CONCACAF", True),
    "MR": CountryMetadata("Mauritania", "MR", "MTN", "CAF", True),
    "MS": CountryMetadata("Montserrat", "MS", "MSR", "CONCACAF", True),
    "MT": CountryMetadata("Malta", "MT", "MLT", "UEFA", True),
    "MU": CountryMetadata("Mauritius", "MU", "MRI", "CAF", True),
    "MV": CountryMetadata("Maldives", "MV", "MDV", "AFC", True),
    "MW": CountryMetadata("Malawi", "MW", "MWI", "CAF", True),
    "MX": CountryMetadata("Mexico", "MX", "MEX", "CONCACAF", True),
    "MY": CountryMetadata("Malaysia", "MY", "MAS", "AFC", True),
    "MZ": CountryMetadata("Mozambique", "MZ", "MOZ", "CAF", True),
    "NA": CountryMetadata("Namibia", "NA", "NAM", "CAF", True),
    "NC": CountryMetadata("New Caledonia", "NC", "NCL", "OFC", True),
    "NE": CountryMetadata("Niger", "NE", "NIG", "CAF", True),
    "NF": CountryMetadata("Norfolk Island", "NF", None, None, False),
    "NG": CountryMetadata("Nigeria", "NG", "NGA", "CAF", True),
    "NI": CountryMetadata("Nicaragua", "NI", "NCA", "CONCACAF", True),
    "NL": CountryMetadata("Netherlands", "NL", "NED", "UEFA", True),
    "NM": CountryMetadata("New Zealand Maori", None, None, None, False),
    "NO": CountryMetadata("Norway", "NO", "NOR", "UEFA", True),
    "NP": CountryMetadata("Nepal", "NP", "NEP", "AFC", True),
    "NR": CountryMetadata("Nauru", "NR", None, None, False),
    "NS": CountryMetadata("Northern Cyprus", None, None, None, False),
    "NU": CountryMetadata("Niue", "NU", None, None, False),
    "NZ": CountryMetadata("New Zealand", "NZ", "NZL", "OFC", True),
    "OM": CountryMetadata("Oman", "OM", "OMA", "AFC", True),
    "PA": CountryMetadata("Panama", "PA", "PAN", "CONCACAF", True),
    "PE": CountryMetadata("Peru", "PE", "PER", "CONMEBOL", True),
    "PF": CountryMetadata("Tahiti", "PF", "TAH", "OFC", True),
    "PG": CountryMetadata("Papua New Guinea", "PG", "PNG", "OFC", True),
    "PH": CountryMetadata("Philippines", "PH", "PHI", "AFC", True),
    "PK": CountryMetadata("Pakistan", "PK", "PAK", "AFC", True),
    "PL": CountryMetadata("Poland", "PL", "POL", "UEFA", True),
    "PM": CountryMetadata("Saint Pierre and Miquelon", "PM", None, None, False),
    "PR": CountryMetadata("Puerto Rico", "PR", "PUR", "CONCACAF", True),
    "PS": CountryMetadata("Palestine", "PS", "PLE", "AFC", True),
    "PT": CountryMetadata("Portugal", "PT", "POR", "UEFA", True),
    "PW": CountryMetadata("Palau", "PW", None, None, False),
    "PY": CountryMetadata("Paraguay", "PY", "PAR", "CONMEBOL", True),
    "QA": CountryMetadata("Qatar", "QA", "QAT", "AFC", True),
    "RE": CountryMetadata("Reunion", "RE", None, None, False),
    "RO": CountryMetadata("Romania", "RO", "ROU", "UEFA", True),
    "RS": CountryMetadata("Serbia", "RS", "SRB", "UEFA", True),
    "RU": CountryMetadata("Russia", "RU", "RUS", "UEFA", True),
    "RW": CountryMetadata("Rwanda", "RW", "RWA", "CAF", True),
    "SA": CountryMetadata("Saudi Arabia", "SA", "KSA", "AFC", True),
    "SB": CountryMetadata("Solomon Islands", "SB", "SOL", "OFC", True),
    "SC": CountryMetadata("Seychelles", "SC", "SEY", "CAF", True),
    "SD": CountryMetadata("Sudan", "SD", "SDN", "CAF", True),
    "SE": CountryMetadata("Sweden", "SE", "SWE", "UEFA", True),
    "SG": CountryMetadata("Singapore", "SG", "SGP", "AFC", True),
    "SH": CountryMetadata("Saint Helena", "SH", None, None, False),
    "SI": CountryMetadata("Slovenia", "SI", "SVN", "UEFA", True),
    "SK": CountryMetadata("Slovakia", "SK", "SVK", "UEFA", True),
    "SL": CountryMetadata("Sierra Leone", "SL", "SLE", "CAF", True),
    "SM": CountryMetadata("San Marino", "SM", "SMR", "UEFA", True),
    "SN": CountryMetadata("Senegal", "SN", "SEN", "CAF", True),
    "SO": CountryMetadata("Somalia", "SO", "SOM", "CAF", True),
    "SQ": CountryMetadata("Scotland", None, "SCO", "UEFA", True),
    "SR": CountryMetadata("Suriname", "SR", "SUR", "CONCACAF", True),
    "SS": CountryMetadata("South Sudan", "SS", "SSD", "CAF", True),
    "ST": CountryMetadata("Sao Tome and Principe", "ST", "STP", "CAF", True),
    "SV": CountryMetadata("El Salvador", "SV", "SLV", "CONCACAF", True),
    "SW": CountryMetadata("Eswatini", "SZ", "SWZ", "CAF", True),
    "SX": CountryMetadata("Sint Maarten", "SX", None, None, False),
    "SY": CountryMetadata("Syria", "SY", "SYR", "AFC", True),
    "SZ": CountryMetadata("Eswatini", "SZ", "SWZ", "CAF", True),
    "TC": CountryMetadata("Turks and Caicos Islands", "TC", "TCA", "CONCACAF", True),
    "TD": CountryMetadata("Chad", "TD", "CHA", "CAF", True),
    "TE": CountryMetadata("Tamil Eelam", None, None, None, False),
    "TG": CountryMetadata("Togo", "TG", "TOG", "CAF", True),
    "TH": CountryMetadata("Thailand", "TH", "THA", "AFC", True),
    "TI": CountryMetadata("Tibet", None, None, None, False),
    "TJ": CountryMetadata("Tajikistan", "TJ", "TJK", "AFC", True),
    "TL": CountryMetadata("Timor-Leste", "TL", "TLS", "AFC", True),
    "TM": CountryMetadata("Turkmenistan", "TM", "TKM", "AFC", True),
    "TN": CountryMetadata("Tunisia", "TN", "TUN", "CAF", True),
    "TO": CountryMetadata("Tonga", "TO", "TGA", "OFC", True),
    "TR": CountryMetadata("Turkey", "TR", "TUR", "UEFA", True),
    "TT": CountryMetadata("Trinidad and Tobago", "TT", "TRI", "CONCACAF", True),
    "TV": CountryMetadata("Tuvalu", "TV", None, None, False),
    "TW": CountryMetadata("Chinese Taipei", "TW", "TPE", "AFC", True),
    "TZ": CountryMetadata("Tanzania", "TZ", "TAN", "CAF", True),
    "UA": CountryMetadata("Ukraine", "UA", "UKR", "UEFA", True),
    "UG": CountryMetadata("Uganda", "UG", "UGA", "CAF", True),
    "US": CountryMetadata("United States", "US", "USA", "CONCACAF", True),
    "UY": CountryMetadata("Uruguay", "UY", "URU", "CONMEBOL", True),
    "UZ": CountryMetadata("Uzbekistan", "UZ", "UZB", "AFC", True),
    "VA": CountryMetadata("Vatican City", "VA", None, None, False),
    "VC": CountryMetadata("Saint Vincent and the Grenadines", "VC", "VIN", "CONCACAF", True),
    "VE": CountryMetadata("Venezuela", "VE", "VEN", "CONMEBOL", True),
    "VG": CountryMetadata("British Virgin Islands", "VG", "VGB", "CONCACAF", True),
    "VI": CountryMetadata("United States Virgin Islands", "VI", "VIR", "CONCACAF", True),
    "VN": CountryMetadata("Vietnam", "VN", "VIE", "AFC", True),
    "VU": CountryMetadata("Vanuatu", "VU", "VAN", "OFC", True),
    "WA": CountryMetadata("Wales", None, "WAL", "UEFA", True),
    "WF": CountryMetadata("Wallis and Futuna", "WF", None, None, False),
    "WS": CountryMetadata("Samoa", "WS", "SAM", "OFC", True),
    "YE": CountryMetadata("Yemen", "YE", "YEM", "AFC", True),
    "YT": CountryMetadata("Mayotte", "YT", None, None, False),
    "ZA": CountryMetadata("South Africa", "ZA", "RSA", "CAF", True),
    "ZM": CountryMetadata("Zambia", "ZM", "ZAM", "CAF", True),
    "ZN": CountryMetadata("Zanzibar", None, None, None, False),
    "ZW": CountryMetadata("Zimbabwe", "ZW", "ZIM", "CAF", True),
}


def get_country_name_from_elo_code(country_code: str) -> str | None:
    """Return canonical country name from an ELO code."""
    metadata = get_country_metadata_from_elo_code(country_code)
    return metadata.canonical_name if metadata else None


def get_country_metadata_from_elo_code(country_code: str) -> CountryMetadata | None:
    """Return normalized country metadata from an ELO code."""
    normalized_code = country_code.strip().upper()
    return COUNTRY_METADATA_MAP.get(normalized_code)