"""add country_code to teams

Revision ID: 3e0e62788fde
Revises: adb1f41d7e16
Create Date: 2026-06-08 13:39:08.117203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e0e62788fde'
down_revision: Union[str, Sequence[str], None] = 'adb1f41d7e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('country_code', sa.String(length=3), nullable=True))
    op.create_index(op.f('ix_teams_country_code'), 'teams', ['country_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_country_code'), table_name='teams')
    op.drop_column('teams', 'country_code')
    # ### end Alembic commands ###
