"""add_is_bet_to_backtest_bets

Revision ID: 931852330f15
Revises: b7a2c9d4e501
Create Date: 2026-06-09 01:09:17.990565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931852330f15'
down_revision: Union[str, Sequence[str], None] = 'b7a2c9d4e501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_bets', sa.Column('is_bet', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_bets', 'is_bet')
    # ### end Alembic commands ###
